export const RoutePaths = {
  HOME: '/home',
  GITHUB_PAGES_HOME_PATH: '/hookah',
  TOBACCO: '/tobacco',
  DARKSIDE: '/darkside-tobacco',
  MUSTHAVE: '/musthave-tobacco',
  ELEMENT: '/element-tobacco',
  TANGIERS: '/tangiers-tobacco',
  FUMARI: '/fumari-tobacco',
  ACCESSORIES: '/accessories',
  NEWS: '/news',
  NEWS_DETAILED: '/news/:id',
  PRODUCT_DETAILED: '/product/:productInfo',
  ABOUT: '/about',
  DELIVERY_POLICY: '/delivery',
  NOT_FOUND: '/not-found',
  FINAL_CHECKOUT: '/checkout',
}
