export const FRONTEND_URL = process.env.REACT_APP_FRONTEND_URL;
export const CONTENTFUL_SPACE_ID = process.env.REACT_APP_CONTENTFUL_SPACE_ID;
export const CONTENTFUL_TOKEN = process.env.REACT_APP_CONTENTFUL_TOKEN;
